manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      #add repo for screen customization
    - name: Crimsonmars
      url-base: https://github.com/Crimsonmars
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
      # support nice_oled and nice_epaper
    - name: zmk-nice-oled
      remote: Crimsonmars
      revision: main
      # hammerbean repo for nice oled
    - name: hammerbeam-slideshow
      remote: Crimsonmars
      revision: main
  self:
    path: config
